comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

language : R
sudo : false
cache : package
after_succes :
-Rcript -e 'covr::codecov()'
